language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
install:
- mkdir installation
- cd installation
- sudo wget http://apt.biicode.com/install.sh 
- sudo chmod +x install.sh 
- sudo ./install.sh
- wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
- tar -xzf cmake-3.0.2-Linux-64.tar.gz
- sudo cp -fR cmake-3.0.2-Linux-64/* /usr
- cd ..
- sudo rm -rf installation
script:
- cmake --version
- bii init biicode_project
- mkdir -p ./biicode_project/blocks/dimitrikourk/small3d
- mv !(biicode_project) ./biicode_project/blocks/dimitrikourk/small3d
- cd biicode_project
- bii find -um
- bii cpp:build 
- "./bin/dimitrikourk_small3d_main"
